---
- hosts: localhost
  gather_facts: false
  roles:
    - extra_vars_check
  vars:
    extra_vars:
      - e_host
      - e_service_name
      - e_jenkins_job_name
      - e_jenkins_build_number

- hosts: '{{ e_host }}'
  name: Deploy Service
  become: true
  vars:
    project_path: "/opt/{{ e_service_name }}"
  tasks:
    - name: Check if target dir exists
      stat:
        path: "{{ project_path }}"
      register: directory_status
      when: directory_status.stat.exists == false

    - name: Create project directory
      file:
        dest: "{{ project_path }}"
        state: directory
        owner: ansible
        group: ansible
        mode: 0755

    - name: Deploy artifact to project directory
      synchronize:
        src:  "/opt/jenkins_jobs/{{ e_jenkins_job_name }}/builds/{{ e_jenkins_build_number }}/archive/Build/"
        dest: "{{ project_path }}"
        owner: false
        group: false

    - name: Restart service
      service:
        name: "{{ e_service_name }}"
        state: restarted
        
    # - name: Add record to DB
    #   # Task for record to DB here

    # - name: Check service HTTP response
    #   # Task for checking service HTTP response here

